POST http://localhost:3000/createUser
Content-Type: application/json

{
    "username": "weily2",
    "password": "weily2",
    "firstname": "Weily2",
    "lastname": "Weily2",
    "dob": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

GET http://localhost:3000/entries/1

### 

GET http://localhost:3000/entry/14/1

###

POST http://localhost:3000/1/new-entry/
Content-Type: application/json

{
    "hours": 7, 
    "day": "2021-03-22",
    "title": "Good afternoon", 
    "description": "Today I woke up again"
}

###
PUT http://localhost:3000/entry/17/1
Content-Type: application/json

{
    "hours": 9
}

###
DELETE http://localhost:3000/delete-entry/1/17